import React, { useState } from "react";
import { FiSend, FiTrash2, FiClock, FiCheckCircle, FiXCircle } from "react-icons/fi";
import { useLabContext } from "../../context/LearningLabContext";

interface APIRequest {
  method: string;
  endpoint: string;
  headers: Record<string, string>;
  body: string;
}

interface APIResponse {
  status: number;
  statusText: string;
  headers: Record<string, string>;
  body: string;
  time: number;
}

interface HistoryEntry {
  request: APIRequest;
  response: APIResponse;
  timestamp: string;
}

const sampleEndpoints: Record<string, { description: string; method: string; sampleBody?: string }> = {
  "/api/chat/completions": { description: "AI Chat Completion", method: "POST", sampleBody: '{\n  "model": "gpt-4",\n  "messages": [\n    { "role": "system", "content": "You are a helpful assistant." },\n    { "role": "user", "content": "Hello!" }\n  ],\n  "temperature": 0.7\n}' },
  "/api/embeddings": { description: "Generate Embeddings", method: "POST", sampleBody: '{\n  "input": "Hello world",\n  "model": "text-embedding-ada-002"\n}' },
  "/api/models": { description: "List Models", method: "GET" },
  "/api/images/generate": { description: "Generate Image", method: "POST", sampleBody: '{\n  "prompt": "A futuristic city at sunset",\n  "size": "1024x1024",\n  "n": 1\n}' },
};

const simulateAPI = (request: APIRequest): APIResponse => {
  const start = performance.now();

  if (!request.endpoint) {
    return { status: 400, statusText: "Bad Request", headers: { "content-type": "application/json" }, body: JSON.stringify({ error: "Endpoint is required" }, null, 2), time: 0 };
  }

  if (request.endpoint.includes("completions")) {
    try {
      const parsed = request.body ? JSON.parse(request.body) : {};
      const userMsg = parsed.messages?.find((m: { role: string }) => m.role === "user")?.content || "Hello";
      return {
        status: 200,
        statusText: "OK",
        headers: { "content-type": "application/json", "x-request-id": "req_" + Math.random().toString(36).slice(2, 10) },
        body: JSON.stringify({
          id: "chatcmpl-" + Math.random().toString(36).slice(2, 10),
          object: "chat.completion",
          model: parsed.model || "gpt-4",
          choices: [{
            index: 0,
            message: { role: "assistant", content: `[Simulated] Response to: "${userMsg}"\n\nThis is a simulated API response. In production, this would be generated by the AI model.` },
            finish_reason: "stop",
          }],
          usage: { prompt_tokens: 25, completion_tokens: 30, total_tokens: 55 },
        }, null, 2),
        time: Math.round(performance.now() - start + 200 + Math.random() * 300),
      };
    } catch {
      return { status: 400, statusText: "Bad Request", headers: { "content-type": "application/json" }, body: JSON.stringify({ error: "Invalid JSON body" }, null, 2), time: Math.round(performance.now() - start) };
    }
  }

  if (request.endpoint.includes("embeddings")) {
    return {
      status: 200, statusText: "OK",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        object: "list",
        data: [{ object: "embedding", index: 0, embedding: Array.from({ length: 8 }, () => parseFloat((Math.random() * 2 - 1).toFixed(6))) }],
        model: "text-embedding-ada-002",
        usage: { prompt_tokens: 4, total_tokens: 4 },
      }, null, 2),
      time: Math.round(performance.now() - start + 100),
    };
  }

  if (request.endpoint.includes("models")) {
    return {
      status: 200, statusText: "OK",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        object: "list",
        data: [
          { id: "gpt-4", object: "model", owned_by: "openai" },
          { id: "gpt-3.5-turbo", object: "model", owned_by: "openai" },
          { id: "text-embedding-ada-002", object: "model", owned_by: "openai" },
          { id: "dall-e-3", object: "model", owned_by: "openai" },
        ],
      }, null, 2),
      time: Math.round(performance.now() - start + 50),
    };
  }

  if (request.endpoint.includes("images")) {
    return {
      status: 200, statusText: "OK",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        created: Date.now(),
        data: [{ url: "https://example.com/generated-image.png", revised_prompt: "[Simulated] Image generation response" }],
      }, null, 2),
      time: Math.round(performance.now() - start + 500 + Math.random() * 500),
    };
  }

  return {
    status: 404, statusText: "Not Found",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ error: `Endpoint "${request.endpoint}" not found. Try: /api/chat/completions, /api/embeddings, /api/models, /api/images/generate` }, null, 2),
    time: Math.round(performance.now() - start),
  };
};

interface APITestingPlaygroundProps {
  phaseId: number;
}

const APITestingPlayground: React.FC<APITestingPlaygroundProps> = ({ phaseId }) => {
  const [method, setMethod] = useState("POST");
  const [endpoint, setEndpoint] = useState("/api/chat/completions");
  const [body, setBody] = useState(sampleEndpoints["/api/chat/completions"].sampleBody || "");
  const [response, setResponse] = useState<APIResponse | null>(null);
  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const [showHistory, setShowHistory] = useState(false);
  const { addLearningTime } = useLabContext();

  const handleSend = () => {
    const request: APIRequest = {
      method,
      endpoint,
      headers: { "Content-Type": "application/json", Authorization: "Bearer sk-demo-***" },
      body,
    };

    // Simulate network delay
    setTimeout(() => {
      const res = simulateAPI(request);
      setResponse(res);
      setHistory((prev) => [
        { request, response: res, timestamp: new Date().toLocaleTimeString() },
        ...prev.slice(0, 9),
      ]);
      addLearningTime(1);
    }, 300);
  };

  const loadEndpoint = (ep: string) => {
    const info = sampleEndpoints[ep];
    if (info) {
      setEndpoint(ep);
      setMethod(info.method);
      setBody(info.sampleBody || "");
      setResponse(null);
    }
  };

  return (
    <div className="bg-gray-100 rounded-xl border border-gray-200">
      {/* Header */}
      <div className="flex items-center justify-between p-3 border-b border-gray-200">
        <div className="flex items-center space-x-2">
          <span className="text-blue-500 text-sm font-medium">🔗 API Testing Playground</span>
          <span className="text-xs text-gray-500">Phase {phaseId}</span>
        </div>
        <button onClick={() => setShowHistory(!showHistory)} className="text-gray-500 hover:text-gray-900 text-xs flex items-center space-x-1 transition-colors">
          <FiClock size={12} />
          <span>{showHistory ? "Hide" : "History"} ({history.length})</span>
        </button>
      </div>

      {/* Quick Endpoints */}
      <div className="p-3 border-b border-gray-200 flex flex-wrap gap-1">
        {Object.entries(sampleEndpoints).map(([ep, info]) => (
          <button
            key={ep}
            onClick={() => loadEndpoint(ep)}
            className={`text-xs px-2 py-1 rounded-full transition-colors ${
              endpoint === ep ? "bg-blue-500 text-gray-900" : "bg-gray-200 text-gray-700 hover:bg-gray-200"
            }`}
          >
            {info.method} {info.description}
          </button>
        ))}
      </div>

      {/* Request */}
      <div className="p-3 space-y-3">
        <div className="flex space-x-2">
          <select value={method} onChange={(e) => setMethod(e.target.value)} className="bg-gray-200 text-gray-900 text-sm rounded px-2 py-2 border border-gray-300">
            <option>GET</option>
            <option>POST</option>
            <option>PUT</option>
            <option>DELETE</option>
          </select>
          <input
            type="text"
            value={endpoint}
            onChange={(e) => setEndpoint(e.target.value)}
            className="flex-1 bg-gray-200 text-gray-900 text-sm rounded px-3 py-2 border border-gray-300 focus:border-blue-500 focus:outline-none"
            placeholder="/api/endpoint"
          />
          <button onClick={handleSend} className="bg-blue-500 text-gray-900 px-4 py-2 rounded hover:bg-blue-600 transition-colors flex items-center space-x-1">
            <FiSend size={14} />
            <span className="text-sm">Send</span>
          </button>
        </div>

        {method !== "GET" && (
          <div>
            <label className="text-gray-500 text-xs mb-1 block">Request Body (JSON)</label>
            <textarea
              value={body}
              onChange={(e) => setBody(e.target.value)}
              rows={6}
              className="w-full bg-white text-green-400 text-xs font-mono rounded p-3 border border-gray-300 focus:border-blue-500 focus:outline-none resize-none"
              placeholder="{ }"
            />
          </div>
        )}

        {/* Response */}
        {response && (
          <div className="border-t border-gray-200 pt-3">
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center space-x-2">
                {response.status < 400 ? (
                  <FiCheckCircle className="text-green-400" size={14} />
                ) : (
                  <FiXCircle className="text-red-400" size={14} />
                )}
                <span className={`text-sm font-medium ${response.status < 400 ? "text-green-400" : "text-red-400"}`}>
                  {response.status} {response.statusText}
                </span>
              </div>
              <span className="text-gray-500 text-xs">{response.time}ms</span>
            </div>
            <div className="bg-white rounded p-3 max-h-64 overflow-y-auto">
              <pre className="text-xs text-gray-700 font-mono whitespace-pre-wrap">{response.body}</pre>
            </div>
          </div>
        )}
      </div>

      {/* History */}
      {showHistory && history.length > 0 && (
        <div className="border-t border-gray-200 p-3">
          <div className="flex items-center justify-between mb-2">
            <span className="text-gray-500 text-xs font-medium">Request History</span>
            <button onClick={() => setHistory([])} className="text-gray-500 hover:text-red-400 transition-colors">
              <FiTrash2 size={12} />
            </button>
          </div>
          <div className="space-y-1 max-h-40 overflow-y-auto">
            {history.map((entry, i) => (
              <button
                key={i}
                onClick={() => {
                  setMethod(entry.request.method);
                  setEndpoint(entry.request.endpoint);
                  setBody(entry.request.body);
                  setResponse(entry.response);
                }}
                className="w-full text-left bg-gray-100 hover:bg-gray-200 rounded px-2 py-1 text-xs flex items-center justify-between transition-colors"
              >
                <span className="text-gray-700">
                  <span className="text-blue-500">{entry.request.method}</span> {entry.request.endpoint}
                </span>
                <span className={entry.response.status < 400 ? "text-green-400" : "text-red-400"}>
                  {entry.response.status} · {entry.response.time}ms
                </span>
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default APITestingPlayground;
